server:
  port: 9000
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      filter:
#        circuit-breaker:
#          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: account-service
#                fallback: forward:/accountServiceFallBack
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: contact-service
#                fallback: forward:/contactServiceFallBack
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: customer-service
#                fallback: forward:/customerServiceFallBack
#hystrix:
#Hystrix Configuration
#hystrix:
#  command:
#    fallback:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info